<a href="https://colab.research.google.com/github/suyash-i7/Everday_learning/blob/main/L1_Learning_4dec_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
###Traditional programme


In [3]:
import numpy as np


In [4]:
1st=[1,0,"hi"]

SyntaxError: invalid decimal literal (ipython-input-825582685.py, line 1)

In [5]:
a=[1,3,"hi",4.0]

In [7]:
x_array=np.array(a)
x_array

array(['1', '3', 'hi', '4.0'], dtype='<U32')

In [8]:
x_array=a_array.shape(-1,1)
x_array

NameError: name 'a_array' is not defined

In [9]:
x_array=a.shape(-1,1)
x_array

AttributeError: 'list' object has no attribute 'shape'

In [10]:
x_array = x_array.reshape(-1, 1)
x_array

TypeError: 'tuple' object is not callable

In [11]:
b=[3,4,5,6]

In [12]:
x_array=np.array(b)
x_array

array([3, 4, 5, 6])

In [13]:
x_array=x_array.shape(1,-1)
x_array

TypeError: 'tuple' object is not callable

In [14]:
from skleran.linear_model import LinearRegression

ModuleNotFoundError: No module named 'skleran'

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model=LinearRegression()

In [17]:
x=[1,2,3,5]
y=[4,8,12,20]

In [18]:
X_arr=np.array(x)
X_arr,type(X_arr)

(array([1, 2, 3, 5]), numpy.ndarray)

In [19]:
X_arr.shape

(4,)

In [20]:
Y_arr=np.array(y)
Y_arr

array([ 4,  8, 12, 20])

In [27]:
X_arr=X_arr.shape(-1,1)
X_arr

TypeError: 'tuple' object is not callable

In [28]:
y_arr=np.array([50,100,-50])
y_arr

array([ 50, 100, -50])

In [29]:
x_arr=np.array([25,50,-50])
x_arr

array([ 25,  50, -50])

In [30]:
X_arr_reshaped = X_arr.reshape(-1, 1)
model.fit(X_arr_reshaped, Y_arr)

AttributeError: 'LinearRegression' object has no attribute 'LinearRegression'